bridge future error:
java.util.concurrent.CancellationException: Future cancelled, response not registered in time, likely due to server disconnect.
	at io.nats.client.support.NatsRequestCompletableFuture.cancelTimedOut(NatsRequestCompletableFuture.java:36)
	at io.nats.client.impl.NatsConnection.lambda$cleanResponses$6(NatsConnection.java:964)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at io.nats.client.impl.NatsConnection.cleanResponses(NatsConnection.java:960)
	at io.nats.client.impl.NatsConnection$2.run(NatsConnection.java:454)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)